### ISSUE TITLE
Incompatible with Python3.4

### ISSUE THREAD

**Issue by mlasevich** [zaibon/py-dmidecode#1]
Even though it claims it is compatible in the setup.py, it is not compatible as it is using subprocess.run() which was added in 3.5 (see [Python Docs](https://docs.python.org/3/library/subprocess.html#using-the-subprocess-module))

**Comment by mlasevich** [comment]
N/P. Thanks for quick review/merge. Not sure how long that takes, but any chance you can push it to pypi so that I can just use the official version rather than pulling from git? Thanks

**Comment by zaibon** [comment]
@mlasevich https://pypi.org/project/py-dmidecode/, there you go
