### ISSUE TITLE
Library should be only parser, not command launcher

### ISSUE THREAD

**Issue by luboss** [zaibon/py-dmidecode#4]
I need to parse dmidecode output from remote systems. Not running the command locally.
Handling command execution, permission level, possible errors and other stuff should be in programmers hand and not parsing library.

**Comment by zaibon** [comment]
The original scope of this package was other. But you have a point, having the `parse` method expose would be a good things so you can reuse it and feed it from whatever source you want.

**Comment by luboss** [comment]
I reorganized the code to pure parsing object, fixed couple of things and added some useful information queries into new functions. Forked version: 
https://github.com/luboss/py-dmidecode/blob/master/dmidecode.py

If you want, I can fork the object to real DMIDecode object that would have the command functionality as you did. Then I can create pull request if you want to incorporate it into your project.

**Comment by zaibon** [comment]
Yep your changes looks very nice, pull request is very welcome. Thanks

**Comment by luboss** [comment]
I updated the code by adding DMIDecode wrapper object which covers running dmidecode locally. I also fixed couple of corner cases and flake8 linter errors.
I created pull request. Somehow I forgot to follow good practise of doing changes in branch so they are in master. Hopefully it won't be an issue for you.

**Comment by luboss** [comment]
Changes have been merged in [pull requests](https://github.com/zaibon/py-dmidecode/commit/194d61dfb9ac7467c2d20044abffc9d655eb944e)
