### ISSUE TITLE
[Python 2.7] super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by 0xE1** [zaibon/py-dmidecode#6]
```
>>> from dmidecode import DMIDecode
>>> import subprocess
>>> dmi = DMIDecode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/dmidecode.py", line 206, in __init__
    super().__init__(raw)
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by 0xE1** [comment]
Changing
`class DMIParse:`
to 
`class DMIParse(object):`
and
`super().__init__(raw)`
to
`super(DMIDecode,self).__init__(raw)`
Solved the issue for me.

**Comment by zaibon** [comment]
Thanks for the report. Python 2.7 is actually not supported but this library at the moment.
I'll have a look see what would have to be adapted to also support this python version.

**Comment by 0xE1** [comment]
I actually got it working with minimal changes from previous comment, as long as changes do not interfere with Python 3, it should work in both.

**Comment by zaibon** [comment]
Now that python2 has officially reach its end of life, I'll close this. :-)

**Comment by 0xE1** [comment]
No complains, I'm glad they committed to actually make this move so we all can move on =)
