### ISSUE TITLE
Support All Wildcard

### ISSUE THREAD

**Issue by jhg03a** [zaibon/py-dmidecode#8]
As a user, I want to get a fully parsed object that's not filtered by the library.  Just like supplying a type name/id, I want to supply a `*` to get all the data.  I can work around this by preparsing the dmidecode output for all the typeid, including the custom OEM ones, available today.

**Comment by zaibon** [comment]
Hi @jhg03a. Sorry for the awfully long response.
I think what you when to do is already possible by using the `data` property that exits on the DMIParse class: https://github.com/zaibon/py-dmidecode/blob/5bda1ae754dbeb96a44431a718967664d342fe42/dmidecode/parse.py#L12

Here is an example code to get the all dump of the command parsed:

```python
from dmidecode import DMIDecode
d = DMIDecode() # execute and parse de dmidecode command
print(d.data) # print the all output parsed
```
